# Set MONGO_BUILD_FOLDER
set(MONGO_BUILD_FOLDER "build/opt")  # Release
if(CMAKE_BUILD_TYPE STREQUAL "Debug") 
    set(MONGO_BUILD_FOLDER "build/debug") 
endif()

# Show configuration summary and build tip
message("")
message(" _______________[ Docutaz configuration summary ]________________")
message("| ")
message("|-- Dependencies:")
message("| ")
message("|   Qt:                 ${Qt6_VERSION}    ${Qt6_DIR}")
message("|   MongoDB:            ${MongoDB_VERSION}    ${MongoDB_DIR}")
message("|   MongoDB Objects:    ${MongoDB_VERSION}    ${MongoDB_OBJECTS_DIR}/${MONGO_BUILD_FOLDER}")
message("|   OpenSSL:            ${OPENSSL_VERSION}    ${OpenSSL_DIR}")
message("|   libssh2:            ${LIBSSH2_VERSION}     (package manager)")
message("|   QScintilla:         ${QSCINTILLA_VERSION}     (package manager)")
message("|   Google Test:        ${GOOGLE_TEST_VERSION}     (FetchContent)")
message("|")
message("|-- Summary:")
message("|")
message("|   Version:            ${PROJECT_VERSION}")
message("|   System:             ${CMAKE_SYSTEM_NAME}")
if (SYSTEM_MACOSX)
    message("|   Target SDK:         ${CMAKE_OSX_DEPLOYMENT_TARGET}")
endif()
message("|   Build type:         ${CMAKE_BUILD_TYPE}")
message("|   Commit:             ${BUILD_NUMBER}")
message("|   Install path:       ${CMAKE_INSTALL_PREFIX}")
message("|")
message("|-- Build, Run and Install:")
message("| ")
message("|     $ bin/build")
message("|     $ bin/run")
message("|     $ bin/install")
message("|")
message("|-- Run Unit Tests:")
message("| ")
message("|     $ bin/build-and-run-tests")
message("|     $ bin/run-tests")
message("|")
message("|-- Run Static Code Analysis:")
message("|")
if (SYSTEM_WINDOWS)
    message("|     $ bin/run-cppcheck <FILE_PATH OR DIR> (Default: /src/docutaz/)")
    message("|     $ bin/run-vs-code-analysis")
else()
    message("|     $ bin/run-clang-tidy")
    message("|     $ bin/run-scan-build")
endif()
message("|__________________________________________________________________")
message("")